name: Call
on: 
  workflow_dispatch:
    inputs:
      task-name:
        type: choice
        options: 
          - 'RunTask1'
          - 'RunTask2'
          - 'RunTask3'
jobs:
  call:
    uses: ./.github/workflows/reuseable.yaml
    with:
      app-environment: develop
      task-name: ${{ inputs.task-name }}
  print:
    needs: [call]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Result > ${MESSAGE}"
        env:
          MESSAGE:  ${{ needs.call.outputs.message }}
