name: Reuseable Workflows
on:
  workflow_call:
    inputs:
      app-environment:
        type: string
        default: develop
        required: true
        description: App Environment [develop staging production]
      task-name:
        type: string
        required: true
        description: run task name
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.app-environment }}:${{ inputs.task-name }}"
      - id: echo-input
        run: echo "body=${{ inputs.app-environment }}:${{ inputs.task-name }}" >> "${GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.echo-input.outputs.body }}

