name: Reuseable Workflows
on:
  workflow_call:
    inputs:
      app-environment:
        type: string
        default: develop
        required: true
        description: App Environment [develop staging production]
      task-name:
        type: string
        required: true
        description: run task name
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo "${{ inputs.app-environment }}:${{ inputs.task-name }}"

      - name: ブランチを決定
        id: select-branch
        run: |
          case "${{ inputs.app-environment }}" in
            develop)
              echo "branch=main" >> "$GITHUB_OUTPUT" 
              ;;
            staging)
              echo "branch=release" >> "$GITHUB_OUTPUT" 
              ;;
            production)
              echo "branch=main" >> "$GITHUB_OUTPUT" 
              ;;
            *)
              echo "Invalid environment provided: ${{ inputs.app-environment }}"
              exit 1
              ;;
          esac

      - name: コードをチェックアウト
        run: echo "checkout to ${{ steps.select-branch.outputs.branch }}"
        # uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   ref: ${{ steps.determine_branch.outputs.branch }}

      - id: echo-input
        run: echo "body=${{ inputs.app-environment }}:${{ inputs.task-name }}" >> "${GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.echo-input.outputs.body }}
